mainapp/urls.py
from django.conf.urls import url
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'


urlpatterns = [
    path('', mainapp.media, name='media'),
    path('<int:pk>/', mainapp.media, name='category'),

]

quastionsapp/urls.py
from django.urls import path

import quastionsapp.views as quastionsapp

app_name = 'quastionsapp'

urlpatterns = [
    path('', quastionsapp.questions, name='questions'),
    path('send_email/', quastionsapp.send_email, name='send_email'),
]

steward/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import mainapp.views as mainapp
import quastionsapp.views as quastionsapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='index'),
    path('about/', mainapp.about, name='about'),
    path('anketa/', include('quastionsapp.urls', namespace='questions')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('documents/', mainapp.documents, name='documents'),
    path('faq/', mainapp.faq, name='faq'),
    path('media/', include('mainapp.urls', namespace='media')),
    path('vacancy/', mainapp.vacancy, name='vacancy'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

class EventCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64,unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активная категория', default=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    category = models.ForeignKey(EventCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя мероприятия', max_length=128)
    image = models.ImageField(upload_to='event_images/', blank=True, null=True)
    short_desc = models.CharField(verbose_name='краткое описание мероприятия', max_length=60, blank=True, null=True)
    description = models.TextField(verbose_name='описание мероприятия', blank=True, null=True)
    timeofevent = models.CharField(verbose_name='дата мероприятия', max_length=60, blank=True, null=True)
    quantity = models.PositiveIntegerField(verbose_name='количество зрителей', default=0, blank=True, null=True)
    is_active = models.BooleanField(verbose_name='активная категория', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)


class Document(models.Model):
    name = models.CharField(verbose_name='имя документа', max_length=128)
    file = models.FileField(upload_to='pdf/', blank=True, null=True)
    short_desc = models.CharField(verbose_name='краткое описание Документа', max_length=60, blank=True, null=True)
    description = models.TextField(verbose_name='описание Документа', blank=True, null=True)

    def __str__(self):
        return self.name

quastionsapp/models.py
from django.db import models

# Create your models here.


class UserContact(models.Model):
    subject = models.CharField(verbose_name='титул', max_length=64, default='Anketa')
    full_name = models.CharField(verbose_name='имя', max_length=64,unique=True)
    age = models.IntegerField(verbose_name='возраст', default=18)
    phone_number = models.CharField(verbose_name='телефон', max_length=64, blank=True)
    city = models.CharField(verbose_name='город', max_length=64, blank=True)
    about = models.TextField(verbose_name='описание', max_length=64, blank=True)
    sender = models.EmailField(verbose_name='email', max_length=254)

    def __str__(self):
        return self.name

quastionsapp/forms.py
from typing import Type

from django import forms

from quastionsapp.models import UserContact
from .models import UserContact
from django.views.generic.detail import DetailView


class ContactForm(DetailView):
    class Meta:
        model = UserContact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

mainapp/views.py
from django.shortcuts import render
from .models import Event, EventCategory, Document
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.

def main(request):
    title = 'главная'

    events = Event.objects.filter(is_active=True, category__is_active=True)[:3]

    content = {
        'title': title,
        'events': events,
    }
    return render(request, 'mainapp/index.html', content)

def about(request):
    title = 'О нас | Стюарды.рф'

    content = {'title': title}

    return render(request, 'mainapp/about.html', content)

# def anketa(request):
#     title = 'Анкета | Стюарды.рф'
#
#     content = {'title': title}
#     return render(request, 'mainapp/anketa.html', content)

def contacts(request):
    title = 'Контакты | Стюарды.рф'

    content = {'title': title}
    return render(request, 'mainapp/contacts.html', content)

def documents(request):
    title = 'Документы | Стюарды.рф'

    documents = Document.objects.all()

    content = {
        'title': title,
        'documents': documents,
    }
    return render(request, 'mainapp/documents.html', content)

def faq(request):
    title = 'FAQ | Стюарды.рф'

    content = {'title': title}
    return render(request, 'mainapp/faq.html', content)

def media(request):
    title = 'Медиа | Стюарды.рф'

    events = Event.objects.filter(is_active=True, category__is_active=True)

    content = {'title': title,
               'events': events,
               }

    return render(request, 'mainapp/media.html', content)

def vacancy(request):
    title = 'Вакансии | Стюарды.рф'

    content = {'title': title}
    return render(request, 'mainapp/vacancy.html', content)

quastionsapp/views.py
from django.shortcuts import render

# Create your views here.
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.conf import settings
from quastionsapp.models import UserContact


# Create your views here.
from django.views.generic import DetailView


def questions(request):
    title = 'Анкета'

    content = {'title': title}

    return render(request, 'quastionsapp/anketa.html', content)


class UserContactView(DetailView):
    model = UserContact
    template_name = 'quastionsapp/anketa.html'



def send_email(request):
    subject = 'Anketa'
    full_name = request.POST.get('full_name', '')
    age = request.POST.get('age', '')
    phone_number = request.POST.get('phone_number', '')
    city = request.POST.get('city', '')
    about = request.POST.get('about', '')
    sender = request.POST.get('sender', '')
    message = f'Данные пользователя {full_name} + {age}+ {phone_number} + {city} + {about} + {sender}'

    if subject and message:
        try:
            send_mail(subject, message, settings.EMAIL_HOST_USER, [settings.EMAIL_HOST_USER], fail_silently=False)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contants/')
    else:
        return HttpResponse('Убедитесь, что все поля заполнены правильно')

# def send_email(request):
#     subject = 'Anketa'
#     full_name = request.POST['full_name']
#     age = request.POST['age']
#     phone_number = request.POST['phone_number']
#     city = request.POST['city']
#     about = request.POST['about']
#     sender = request.POST['sender']
#     message = full_name + age + phone_number + city + about + sender
#
#     if subject and message:
#         try:
#             send_mail(subject, message, settings.EMAIL_HOST_USER, settings.EMAIL_HOST_USER, fail_silently=False)
#         except BadHeaderError:
#             return HttpResponse('Invalid header found.')
#         return HttpResponseRedirect('/contants/')
#     else:
#         return HttpResponse('Убедитесь, что все поля заполнены правильно')

mainapp/templates/mainapp/about.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

    {% block content %}
        <<div class="contentHeader newProductsHeader">
                    О нас
        </div>
            <div class="containerText">
                Наша компания <strong>ООО "Профи сервис"</strong>
                имеет многолетний опыт работы в организации и обеспечении
                спортивно-массовых мероприятий. Мы имеем в своем составе квалифицированные
                управленческие кадры и подготовленный личный состав. Менеджмент и персонал
                неоднократно получали положительную оценку в работе от правоохранительных
                органов города Москвы, Европейской Федерации Футбола <b>УЕФА</b>. <br> <br>
                Компания постоянно совершенствует уровень и качество своей работы. С этой целью
                производится модернизация материально-технической базы, систематизация учебного
                процесса менеджмента и персонала.<br> <br> Наш головной офис расположен на территории
                Центрального стадиона <b>«Локомотив»</b>. Взаимодействуя на договорной основе по вопросам
                обеспечения спортивно-массовых мероприятий, наша организация является надёжным партнером
                футбольного клуба <b>«Локомотив»</b>. С каждым годом наша компания укрепляет свои позиции
                в данной сфере. Результаты нашей работы позволяют поддерживать долгосрочное сотрудничество,
                находя положительный отклик у заказчиков.
            </div>
    {% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title%}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery/jquery-1.12.4.min.js' %} "></script>
        <script src="{% static 'style/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>

    {% endblock %}
</head>
<body>
    {% block header %}
        <div class="header">
            <div class="container">
                <nav class="navbar navbar-default xsNavBar visible-xs">
                    <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                          <a class="navbar-brand xsLogo" href="{% url 'index' %}">Steward</a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                            {% include 'mainapp/includes/inc_menu.html' %}
                          </ul>
                        </div>
                    </div><!-- /.container-fluid -->
                </nav>
                <a href="{% url 'index' %}" class="logo hidden-xs"></a>
                <div class="welcomeWrap">
                    <div class="welcome">
                        Добро пожаловать в стюарды
                    </div>
                    <div class="welcomeText">
                        Ни одно мероприятие не проходит
                        без нашего участия,
                        стань и ты частью нашей команды
                    </div>
                </div>
                <div class="funrideWrap">
                    <div class="funrideHead">
                            Сезон <br>
                            2018-2019
                    </div>
                    <div class="funrideText">
                            Вы побывайте на удивительных событиях<br>
                            от мачтей лиги чемпионов<br>
                            до концертов звезд, найдете новых друзей<br>
                            и станете частью прекрасной команды
                    </div>
                    <a class="funrideButton" href="{% url 'questions:questions' %}"> Заполнить анкету </a>
                </div>
                <div class="socialIconsWrap">
                    <a href="https://www.facebook.com/stewards.rus.73" target="_blank">
                        <i class="fa fa-facebook-f fa-lg"></i>
                    </a>
                    <a href="https://vk.com/stewards_rus" target="_blank">
                        <i class="fa fa-vkontakte fa-vk"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-youtube fa-lg"></i>
                    </a>
                    <a href="mailto:hr@стюарды.рф" target="_blank">
                        <i class="fa fa-mail fa-lg"></i>
                    </a>
                    <a href="https://www.instagram.com/stewards_rus/?utm_source=ig_profile_share&igshid=1fq2d9rtvpolp" target="_blank">
                        <i class="fa fa-instagram fa-lg"></i>
                    </a>
                </div>
            </div>
        </div>
    {% endblock %}
    <div class="container content">
        <div class="row">
             <div class="col-lg-3 col-sm-4">
                <ul class="hidden-xs mainMenu">
                    {% include 'mainapp/includes/inc_menu.html' %}
                </ul>
                <!--<div class="nowIsOpen">-->
                    <!--<div class="nowIsOpenInside">-->
                        <!--<span>-->
                            <!--Скоро<br>-->
                            <!--это<br>-->
                            <!--будет!-->
                        <!--</span>-->
                    <!--</div>-->
                <!--</div>-->
            </div>
            <div class="col-lg-9 col-md-8 col-sm-8 ">
            {% block content %}

            {% endblock %}
            </div>

        </div>
    </div>
    {% block sponsor %}
        <div class="row">
            <div class="container-fluid">
                <div id="brand1" class="brands">
                    <a href="http://www.rfs.ru/" target="_blank"> <img src="{% static 'images/brands/rfs.png' %}" alt="rfs"> </a>
                    <a href="https://premierliga.ru/" target="_blank"><img src="{% static 'images/brands/rpl.png' %}" alt="rpl"></a>
                    <a href="https://www.fclm.ru/ru/" target="_blank"><img src="{% static 'images/brands/loko.png' %}" alt=""></a>
                    <a href="http://fckazanka.ru/" target="_blank"><img src="{% static 'images/brands/kazanka_0.png' %}" alt="kazanka"></a>
                    <a href="https://ponominalu.ru/" target="_blank"><img class="hidden-md" src="{% static 'images/brands/logo-ponominalu.png' %}" alt="ponominalu"></a>
                    <a href="http://stadion-spartakovets.ru/" target="_blank"><img src="{% static 'images/brands/httpstadion_spartakovetsru.png' %}" alt="Стадион Спартаковец"></a>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block footer %}
        <div class="instagramFeedWrap">
            <div class="instaFeedHead">
                <i class="fa fa-instagram"></i>
                <span>Instagram feed:</span> #стюардыРФ
            </div>
                <div class="instaFeedImages">
                    <img src="{% static 'images/instaFeed/1.jpg' %}" alt="">
                    <img src="{% static 'images/instaFeed/2.jpg' %}" alt="">
                    <img src="{% static 'images/instaFeed/3.jpg' %}" alt="">
                    <img src="{% static 'images/instaFeed/4.jpg' %}" alt="">
                    <img src="{% static 'images/instaFeed/5.jpg' %}" alt="">
                </div>
            </div>
            <div class="socialButtonsWrap">
                <a href="https://www.facebook.com/stewards.rus.73" target="_blank">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="https://vk.com/stewards_rus" target="_blank">
                    <i class="fa fa-vk"></i>
                </a>
                <a href="https://www.instagram.com/stewards_rus/?utm_source=ig_profile_share&igshid=1fq2d9rtvpolp" target="_blank">
                    <i class="fa fa-instagram"></i>
                </a>
            </div>
            <div class="footer">
                <div class="container footerInside">
                    <div class="footerColumn">
                        <div class="columnHead">
                            Категории
                        </div>
                        <div class="columnLinks">
                            {% include 'mainapp/includes/inc_mini_menu.html' %}
                        </div>
                    </div>
                    <div class="footerColumn about">
                        <div class="columnHead">
                            О нас
                        </div>
                        <div class="columnAboutUs">
                            <div class="aboutText">
                                Мы всегда на связи!
                                По вопросам трудоустройства просим обращаться
                                с 12:00 по 18:00 по телефонам:
                            </div>
                            <div class="aboutPhone">
                                <span>Phone:</span> 8-925-898-47-85 <br>
                                <span>Phone:</span> 8-967-010-65-31 <br>
                                <span>Phone:</span> 8-499-343-68-53
                            </div>
                            <div class="aboutEmail">
                                <span>E-mail:</span> hr@стюарды.рф
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="footerCopyrights">
            <div class="container copyrightsInside">
                <div class="footerCopySign">
                    &copy; 2018  Стюарды.рф All rights reserved <span class="hidden-xs"></span><br class="visible-xs">
                </div>
                <div class="footerSocials">
                    <i class="fa fa-facebook"></i>
                    <i class="fa fa-vk"></i>
                    <i class="fa fa-mail"></i>
                    <i class="fa fa-instagram"></i>
                    <i class="fa fa-feed"></i>
                </div>
            </div>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
    {% block content %}
            <div class="contentHeader newProductsHeader">
                Контакты
            </div>

            <div class="containerText">
               <p>По вопросам трудоустройства можете связаться с нами по следующим телефонам с 10:00 до 21:00<br>
                <ul>
                <li class="fa fa-phone-square"> 8-925-898-47-85 </li> <br>
                <li class="fa fa-phone-square"> 8-967-010-65-31 </li> <br>
                <li class="fa fa-phone-square"> 8-499-343-68-53 </li> <br>
                </ul>
                Так же вы можете обраться к нам через электронную почту steward@стюарды.рф или
                через социальные сети
                <a href="#">
                 <i class="fa fa-facebook-f fa-lg"></i>
                </a> ,
                <a href="#">
                    <i class="fa fa-vkontakte fa-vk"></i>
                </a>.
                <p>
                Либо придти к нам в гости, добравшись до станции метро Черкизовская (удобнее последний вагон из центра) и следовать маршруту на карте:
                </p><br>
                <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ac4f51313a51da838a3c014c961bc22b6f885fca3eb99900a14c80846f0e1f319&amp;width=100%25&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
            </div>

    {% endblock %}

mainapp/templates/mainapp/documents.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


    {% block content %}
        <div class="contentHeader newProductsHeader">
                    Нормативные документы
        </div>
            <div class="row">
            {% for document in documents %}
                <div class="col-lg-6 col-md-8 productUnitCol">
                    <div class="productUnit">
                        <div class="productCornerNew">new</div>
                        <a href="/media/{{ document.file }}" target="_blank"><img class="productImg" src="/static/images/stewardsLogo.png" alt="{{ document.short_desc }}"></a>
                        <div class="nameAndPriceWrap">
                            <div class="productName">
                                Lorem ipsum dolor sit. {{ document.name }}
                            </div>
                            <div class="productPriceWrap">
                                <div class="actualPrice">
                                    {{ document.description }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}

mainapp/templates/mainapp/includes/inc_menu.html
<li class="active"><a href="{% url 'index' %}">Меню <span class="sr-only">(current)</span></a></li>
<li><a href="{% url 'about' %}">О нас</a></li>
<li><a href="{% url 'media:media' %}">Медиа</a></li>
<li><a href="{% url 'vacancy' %}">Вакансии</a></li>
<li><a href="{% url 'questions:questions' %}">Анкета</a></li>
<li><a href="{% url 'documents' %}">Документы</a></li>
<li><a href="{% url 'contacts' %}">Контакты</a></li>
<li><a href="#brand1">Партнеры</a></li>
<li><a href="{% url 'faq' %}">FAQ</a></li>

mainapp/templates/mainapp/includes/inc_mini_menu.html
<a href="{% url 'index' %}">Меню </a>
<a href="{% url 'about' %}">О нас</a>
<a href="{% url 'media:media' %}">Медиа</a>
<a href="{% url 'vacancy' %}">Вакансии</a>
<a href="{% url 'questions:questions' %}">Анкета</a>
<a href="{% url 'documents' %}">Документы</a>
<a href="{% url 'contacts' %}">Контакты</a>
<a href="#brand1">Партнеры</a>
<a href="{% url 'faq' %}">FAQ</a>

mainapp/templates/mainapp/media.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

    {% block content %}
        <div class="contentHeader newProductsHeader">
            Медиа с мероприятий
        </div>
        <div class="row">
            {% for event in events %}
                    <div class="col-lg-6 col-md-8 productUnitCol">
                        <div class="productUnit">
                            <div class="productCornerNew">new</div>
                            <img class="productImg" src="/media/{{ event.image }}" alt="{{ event.short_desc }}">
                            <div class="nameAndPriceWrap">
                                <div class="productName">
                                    {{ event.name }}
                                </div>
                                <div class="productPriceWrap">
                                    <div class="actualPrice">
                                        12.11.2018
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    {% endblock %}

quastionsapp/templates/quastionsapp/anketa.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

    {% block content %}
                <div class="contentHeader newProductsHeader">
                    Заполни анкету
                </div>
                    <div class="containerText">
                        <p><b>Прежде чем заполнять <i>анкету</i>, прочтите, пожалуйста, требования к кандидатам в контролеры -распорядители:</b></p>
                       <p>Кандидат на должность контролера-распорядителя должен соответствовать требованиям, установленным частью 2 статьи 20.2 Федерального закона «О физической культуре и спорте в Российской Федерации» и не может быть: <br>
                        <ul>
                        <li> лицом, не имеющим гражданства Российской Федерации; </li>
                        <li> гражданином Российской Федерации, признанным вступившим в законную силу решением суда недееспособным, ограниченно дееспособным;</li>
                        <li> гражданином Российской Федерации, не достигшим возраста восемнадцати лет; </li>
                        <li> лицом, имеющим неснятую и непогашенную судимость, а также лицом, привлекавшимся к административной ответственности за административные правонарушения, предусмотренные статьей 20.31 Кодекса Российской Федерации об административных правонарушениях, в течение срока, во время которого он считается подвергнутыми административному наказанию; </li>
                        <li> лицом, состоящим на учете в организациях органов здравоохранения по поводу психического заболевания, алкоголизма, наркомании или токсикомании.</li>
                        </ul>
                        </p><br>
                </div>
                <div class="contentHeader newProductsHeader" id="anketa">
                            Анкета
                </div>
                    <div class="containerText">
                        <p><b>Скачиваем, заполняем <i>анкету</i> и отправляем ее нам на почту <a href="mailto:hr@стюарды.рф">hr@стюарды.рф</a>!</b></p>
                    </div>
                        <div class="row">
                            <div class="col-lg-4 col-md-6 productUnitCol">
                                <div class="productUnit">
                                    <div class="productCornerNew">xlsx</div>
                                    <a href="/static/pdf/anketa_2019.xlsx" target="_blank"><img class="productImg" src="{% static 'images/stewardsLogo.png' %}" alt="Анкета для заполнения"></a>
                                    <div class="nameAndPriceWrap">
                                        <div class="productName">
                                            Анкета для заполнения
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>

                <div class="row">
                    <div class="col-lg-0 col-md-12 productUnitCol">
                        <form action="{% url 'questions:send_email' %}" method="post" class="">

                            {% csrf_token %}
<!--                            <input type="hidden" name="_token" value="4KH1atxl9qrL3lNGa9CnutVYRSeXs9kv0sjZP4Iy">-->
<!--                            <input name="subject" type="hidden" value="index">-->
                            <div class="form-group">
                                <label for="full_name">Фамилия, Имя:</label>
                                <input name="full_name" type="text" value="{{full_name}}" class="form-control inpot" id="name" required="" placeholder="">
                            </div>
                            <div class="form-group">
                                <label for="sender">E-mail:</label>
                                <input name="sender" type="text" value="{{sender}}" class="form-control inpot" id="sender" required="" placeholder="">
                            </div>
                            <div class="form-group">
                                <label for="age">Возраст:</label>
                                <input name="age" type="number" value="{{age}}" class="form-control" id="age" min="18" max="60" placeholder="Для соискателей  старше 18 лет" required="">
                            </div>
                            <div class="form-group">
                                <label for="phone_number">Номер телефона</label>
                                <input name="phone_number" value="{{phone_number}}" type="tel" class="form-control" id="phone_number" required="">
                            </div>
                            <div class="form-group">
                                <label for="city">Город проживания:</label>
                                <input name="city" value="{{city}}" type="text" class="form-control" id="city" required="">
                            </div>
<!--                            <div class="form-group">-->
<!--                                <label for="additionally">Дополнительная информация о себе (кратко):</label>-->
<!--                                <textarea name="about" type="textarea" class="form-control" id="additionally" maxlength="160" rows="2" cols="100"></textarea>-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label class="custom-control custom-checkbox">-->
<!--                                    <input type="checkbox" class="custom-control-input" required="">-->
<!--                                    <span class="custom-control-indicator mt-lg-1"></span>-->
<!--                                    <span class="custom-control-description">*Согласен на обработку своих персональных данных:</a></span>-->
<!--                                </label>-->
<!--                            </div>-->
                            <div class="d-flex justify-content-center">
                                <button class="btn btn-danger form-sub" type="submit" id="go">ОТПРАВИТЬ</button>
                            </div>
                        </form>


                    </div>
                </div>
    {% endblock %}